export default {
  // Target (https://go.nuxtjs.dev/config-target)
  // default to `server` unless the `NUXT_BUILD_TARGET` var has been defined.
  target: process.env.NUXT_BUILD_TARGET || 'server',

  // Global page headers (https://go.nuxtjs.dev/config-head)
  head: {
    title: 'UniformConf',
    description: 'UniformConf, a Uniform Optimize demo site',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'UniformConf, a Uniform Optimize demo site' },
      { hid: 'og:description', name: 'og:description', content: 'UniformConf, a Uniform Optimize demo site' },
      { hid: 'og:site_name', name: 'og:site_name', content: 'uniformconf.com' },
      {
        hid: 'apple-mobile-web-app-title',
        name: 'apple-mobile-web-app-title',
        content: 'UniformConf',
      },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  // Global CSS (https://go.nuxtjs.dev/config-css)
  css: [],

  // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: ['~/plugins/contentful-nuxt-plugin.js', '~/plugins/preview.client.js'],

  // Auto import components (https://go.nuxtjs.dev/config-components)
  components: true,

  // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
  ],

  // Modules (https://go.nuxtjs.dev/config-modules)
  modules: [
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    'cookie-universal-nuxt',
    '~/modules/uniform/optimize/initialize.js',
  ],

  // Build Configuration (https://go.nuxtjs.dev/config-build)
  build: {},
  publicRuntimeConfig: {
    CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
    CONTENTFUL_CDA_ACCESS_TOKEN: process.env.CONTENTFUL_CDA_ACCESS_TOKEN,
    CONTENTFUL_ENVIRONMENT: process.env.CONTENTFUL_ENVIRONMENT,
    GA_UA_ID: process.env.GA_UA_ID,
    SEGMENT_ID: process.env.SEGMENT_ID,
  },
  generate: {
    crawler: false,
    routes: ['/', '/developers', '/marketers', '/registration'],
    fallback: true,
    dir: 'out',
    cache: {
      globbyOptions: {
        // IMPORTANT: When using nuxt generate with static target, a snapshot including checksum of
        // non-ignored project files as well as nuxt version and some other configuration will be
        // written to a .nuxt/build.json file at build time.
        // Subsequent builds will compare the previous build.json to current build.json and determine
        // whether a full Nuxt rebuild needs to occur.
        // By default, the Nuxt build snapshot generator will respect _any_ .gitignore files that
        // exist in the app, which causes a problem for Uniform Optimize because there is a .gitignore
        // file in place that excludes the `intentManifest.json` file that is generated by Uniform CLI
        // at static export time.
        // Unfortunately, Nuxt does provide an easy way to bypass this behavior, so (for now) we
        // set the following `gitignore` option to false so that .gitignore files will _not_
        // be processed when Nuxt generates build snapshots.
        gitignore: false,
      },
    },
  },
};
